from faker import Faker
from collections import namedtuple
import time
import datetime

faker = Faker()

NUM_PROFILE = 10000
Profile = namedtuple('Profile', 'job, company, ssn, residence, current_location, blood_group, website, username, name, sex, address, mail, birthdate')
Profile.__doc__ = "Profile namedtuple that contains the fake profile fields generated by faker library"
Profile.name.__doc__ = "Name of the person"
Profile.job.__doc__ = "Job designation of the person"
Profile.company.__doc__ = "Company where the person is employed in"
Profile.ssn.__doc__ = "Social security number of the person"
Profile.residence.__doc__ = "Residence of the person"
Profile.current_location.__doc__ = "Current location coordinates (latitude, longitude) of the person"
Profile.blood_group.__doc__ = "Blood group of the person"
Profile.website.__doc__ = "List of websites of the person"
Profile.address.__doc__ = "address of the person"
Profile.username.__doc__ = "username of the person"
Profile.sex.__doc__ = "Gender of the person"
Profile.mail.__doc__ = "E-mail address of the person"
Profile.birthdate.__doc__ = "birthdate of the person"

ProfileList = namedtuple('ProfileList', list(range(NUM_PROFILE)), rename=True)
ProfileList.__doc__ = "ProfileList namedtuple that contains all the entries of profiles as a separate field whose name is _1, _2 etc"


def form_profile_named_tuple() -> ProfileList:
    """
    Function to form the namedtuple which contains 10000 generated fake profiles
    :return: namedtuple which contains generated fake profiles
    """
    profile_tuple_list = list()
    for i in range(NUM_PROFILE):
        profile_tuple_list.append(Profile(**faker.profile()))
    profileList = ProfileList(*profile_tuple_list)
    return profileList


def calculate_largest_blood_type(profileList) -> tuple:
    """
    Function to calculate the blood type with most number of people
    :param profileList: namedtuple which contains generated fake profiles
    :return: tuple of blood type with most number of people and time taken to execute this function
    """
    start_time = time.time()
    grp_count = {}
    for profile in profileList:
        grp = profile.blood_group
        count = grp_count.get(grp, 0)
        count += 1
        grp_count[grp] = count
        # print(grp_count)
    max_blood_grp = max(grp_count, key = grp_count.get)
    # print(max_blood_grp)
    end_time = time.time()
    return max_blood_grp, end_time-start_time


def calculate_mean_current_location(profileList) -> tuple:
    """
    Function to mean current location
    :param profileList: namedtuple which contains generated fake profiles
    :return: tuple of mean current location (which is a tuple of latitude and longitude coordinates)
    and time taken to execute this function
    """
    start_time = time.time()
    sum_x = 0
    sum_y = 0
    for profile in profileList:
        sum_x += profile.current_location[0]
        sum_y += profile.current_location[1]
    mean_current_location = sum_x/ len(profileList), sum_y / len(profileList)
    end_time = time.time()
    return mean_current_location, end_time - start_time


def calculate_oldest_person_age(profileList) -> tuple:
    """
    Function to oldest person age
    :param profileList: namedtuple which contains generated fake profiles
    :return: tuple of oldest person age and time taken to execute this function
    """
    start_time = time.time()
    max_age = max((datetime.date.today() - profile.birthdate).days for profile in profileList) / 365.25
    end_time = time.time()
    return max_age, end_time - start_time


def calculate_avg_age(profileList) -> tuple:
    """
    Function to average person age
    :param profileList: namedtuple which contains generated fake profiles
    :return: tuple of average person age and time taken to execute this function
    """
    start_time = time.time()
    avg_age = sum((datetime.date.today() - profile.birthdate).days for profile in profileList) / len(profileList) / 365.25
    end_time = time.time()
    return avg_age, end_time - start_time